name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu_latest

    steps:
    - uses: actions/checkout@v3
    - name: mkdir_build
      run:  mkdir build
    - name: cd_build
      run:  cd build
    - name: cmake
      run:  cmake /home/runner/work/CppNet/CppNet
    - name: make
      run:  make
  build_windows:
    runs-on: windows_latest

    steps:
    - uses: actions/checkout@v3
    - name: mkdir_build
      run:  mkdir build
    - name: cd_build
      run:  cd build
    - name: cmake
      run:  cmake D:\a\CppNet\CppNet
    - name: make
      run:  make
  build_mac:
    runs-on: mac_latest

    steps:
    - uses: actions/checkout@v3
    - name: mkdir_build
      run:  mkdir build
    - name: cd_build
      run:  cd build
    - name: cmake
      run:  cmake /home/runner/work/CppNet/CppNet
    - name: make
      run:  make
      
