name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, mac_latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: mkdir_build
      run:  mkdir build
    - name: cd_build
      run:  cd build
    - name: cmake
      run:  cmake ..
    - name: make
      run:  make
      
